require 'starscourge.ui.tree'
require 'starscourge.ui.git'
require 'starscourge.ui.lualine'
require 'starscourge.ui.components'
require 'starscourge.ui.barbar'
require 'starscourge.ui.dashboard'
require 'starscourge.ui.telescope'
require 'starscourge.ui.statuscolumn'
